### ISSUE TITLE
Failed to remove element

### ISSUE THREAD

**Issue by rhardih** [rhardih/ekill#34]
"Must Read Stories" popup in the page bottom generates an invalid selector:

https://deadline.com/2019/10/bone-netflix-will-animate-jeff-smith-acclaimed-comic-book-epic-1202761594/

Error:
```
DOMException: Failed to execute 'querySelectorAll' on 'Document': '.toaster.u-width-100p.u-hidden@desktop-max' is not a valid selector.
    at Object.ekill.elementHierarchyToDOMString (chrome-extension://lcgdpfaiipaelnpepigdafiogebaeedg/js/testable.js:130:13)
    at chrome-extension://lcgdpfaiipaelnpepigdafiogebaeedg/js/ekill.js:135:34
```

**Comment by Perruer** [comment]
This (and #30) is fixed in SkullClick, a maintained Manifest V3 fork of ekill that I made: ids and classes are now escaped with `CSS.escape`, so classes like `u-hidden@desktop-max` or `js-comp-ver-5.7` produce valid selectors (there are unit tests for both cases).

https://github.com/Perruer/skullclick
